apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  namespace: kirtus
spec:
  type: LoadBalancer
  selector:
    app: mongo-express
  ports:
    - port: 80
      targetPort: 8081
  loadBalancerIP: 172.16.10.202
