apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:6
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"  # Set your root username
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "Aa17935!"  # Set your root password
      volumes:
        - name: mongo-data
          emptyDir: {}