apiVersion: batch/v1
kind: Job
metadata:
  name: patch-mongo-pvs
  namespace: mongodb
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 2
  template:
    spec:
      serviceAccountName: pv-patch-sa
      containers:
        - name: pv-patcher
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "🔍 Scanning for Released Mongo PVs..."
              for pv in $(kubectl get pv -o jsonpath='{range .items[*]}{.metadata.name}{"\t"}{.spec.claimRef.namespace}{"\t"}{.spec.claimRef.name}{"\t"}{.status.phase}{"\n"}{end}' | grep '^pvc' | grep 'mongodb' | grep 'Released' | awk '{print $1}'); do
                echo "🛠️ Patching PV $pv..."
                kubectl patch pv $pv -p '{"spec":{"claimRef": null}}'
              done
      restartPolicy: OnFailure
