apiVersion: v1
kind: ServiceAccount
metadata:
  name: pv-patch-sa
  namespace: mongodb
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pv-patch-role
  namespace: mongodb
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pv-patch-rolebinding
  namespace: mongodb
  annotations:
    argocd.argoproj.io/sync-wave: "0"
subjects:
  - kind: ServiceAccount
    name: pv-patch-sa
    namespace: mongodb
roleRef:
  kind: Role
  name: pv-patch-role
  apiGroup: rbac.authorization.k8s.io
