---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongo-secret
  namespace: mongodb
spec:
  encryptedData:
    MONGO_INITDB_ROOT_PASSWORD: AgDDuqloUxz5bkOS4I1rAvHOomWZ/P8+YlsD6rRgMGZKNIivO1S3CAhXSQfB1loYLEHyTS7YlAVULxIP6GJ3NxYkrQUdywO82de9BZMQJU5wpmGm7gAGQLAkwup0FA6egrDtEODA7p9hjPFI0CRqXbqSjdEqELB7kaAYOm/BKWuL6cb2FEbz5szfzoM4UaGHfMy7E+CVDmggvOiks3Pj/M29okfGEb6jvoAatzMrOnwAr2u+LAXXweys7KCuOIzp4PKpFjd7i6ePgvei4AvtrjfOiPPo0P78O1FpcTGMvCxcpkghjzHcOPoE6/OSJzb6zqUquRtdvKJv+Jid1uaWH0R+MxnfuczwgdQ2zbWftZAQCKH0mk0KrgYvLTUX3+7JXQSbFehabtIIxcKFKRj5nFwr3h5eW8iXTVqPkLmd7c5zhWlJv5OU1Fx5292MQsHJj/nC6Id/z6/GbUoD5cYIxpc5Hvuk96Q1xKtvFWb8FXhks9XKUhLbOUOwp6OYy8Y1rPGJOsPaLOnzwObSCBfZoEECNr4nW/8zJB+LP7yCKHgCBD1DKxFtMOZWKnSTpPpac5v2K7zkWQNDUh0dIrlwueA35lGUbqivpvrhk2lOVJf9snshwaJWmuua1K7hg+nSiCj8rvxC/c+b3lEjQFnHpppfTR/RDDD24MYOp7Dek1LZBgc1+cVgoCJcjsF8MgfTLUBlL0oL7Kak7g==
    MONGO_INITDB_ROOT_USERNAME: AgCVkb+JJT+S3iIF+8bL/te5YiNgUjPjSup0s0Fher+uigr+2r1aisbcr9H8e/GugeN4/m5F7e94OaNi5vZZbFzohEC0hHwEAYeMhY4b0GTqUInRWP7cZg+xC68nHGq6KGdv0JoBCr2MVwUNGHLkRQFkQqzJbOD/JKZwnFQtoOkeE94i6KF72OcLe/XzJeziN/EHRf9HG7fQeQW9HuT7Nfsu+JPvvPDhyXSxyxk4hdkwkjaKTgbHM3POtdNI6Qcmit2JqZaLh9lMg/TnZkY/0UOZyN0JlDTPfd9GsufBSqjpemjdSVZvGRHbFXTbXzLLh5zroyrgUKBJpfoQdpCcLTi6p73HMeyDLRoZFex/imSgtNV6Fh1IURnyFBB0g+LBr56nWEPYE/TKJixMhjSNyql60GOlhious1DxsrgWLt84+FvnUBBuAeDtr2ie4hBM+Md3HxfzKxJ8FBjdFX1fqZNBxQmxbq6FGnnlRd5jLvkisvf7k6HAnu6EJeuk7LLtJc/h45WyN33yn+/3DUt+rnDQ0t0FYl5pdFcPmkItDINpSPq0PrQms/MahrZG1/1bABhTGDPMd9ujE+O06HagmdgSw4pwfCL1c+1mqVVNtAeBWip7Tl/0Nr7cuJeLU/n5I94Nr5iNKpQFL9/VkUs93BKOlX9WjO0CtIhe6+k8eZ5Mr2B5RTsMjZi30HI3hWmvjbs+VVJ13w==
  template:
    metadata:
      creationTimestamp: null
      name: mongo-secret
      namespace: mongodb
    type: Opaque
