apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: mongodb
  labels:
    app: mongo
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: Aa17935!
