apiVersion: v1
kind: Secret
metadata:
  name: mongo-express-secret
  namespace: mongodb
type: Opaque
stringData:
  MONGO_URI: "mongodb://admin:Aa17935%21@mongo-0.mongo-headless.mongodb.svc.cluster.local:27017,mongo-1.mongo-headless.mongodb.svc.cluster.local:27017,mongo-2.mongo-headless.mongodb.svc.cluster.local:27017/admin?replicaSet=rs0"
