apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: mongodb
spec:
  selector:
    app: mongo
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-headless
  namespace: mongodb
spec:
  clusterIP: None
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
