apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: mongodb
  labels:
    app: mongo
spec:
  clusterIP: None  # Headless service!
  selector:
    app: mongo
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
