apiVersion: v1
kind: Service
metadata:
  name: portainer
  namespace: portainer
spec:
  type: LoadBalancer
  selector:
    app: portainer
  ports:
    - protocol: TCP
      port: 9443
      targetPort: 9000
  LoadBalancerIP: 172.16.10.205
