apiVersion: apps/v1
kind: Deployment
metadata:
  name: keepass-app
  namespace: keepass
  labels:
    app: keepass
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keepass
  template:
    metadata:
      labels:
        app: keepass
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "3001"
    spec:
      containers:
        - name: keepassecure
          image: bene1310/keepassscure:v1.0.2
          ports:
            - containerPort: 3001
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret-keepass
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret-keepass
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_REPLICA_SET
              value: "rs0"
