apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-metrics
  namespace: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-metrics
  template:
    metadata:
      labels:
        app: flask-metrics
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: flask-metrics
          image: bene1310/sample-flask-app:v1.0.1
          ports:
            - containerPort: 8000
