# prometheus-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
    
      
      - job_name: 'node-exporter'
        static_configs:
          - targets:
              - 172.16.10.51:9100
              - 172.16.10.52:9100
              - 172.16.10.53:9100

      - job_name: 'wmi_exporter'
        static_configs:
          - targets:
              - 172.16.10.108:9182

      - job_name: 'python'
        static_configs:
          - targets:
              - 172.16.10.108:8000

      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            target_label: __address__
            regex: (.+):(?:\d+);(\d+)
            replacement: ${1}:${2}
      
    rule_files:
      - "/etc/prometheus/rules/alerts.yml"
      - "/etc/prometheus/rules/recording_rules.yml"
      
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
                - alertmanager.prometheus.svc:9093