# prometheus-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.52.0
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus/
            - name: rules-volume
              mountPath: /etc/prometheus/rules/alerts.yml
              subPath: alerts.yml
              readOnly: true
            - name: recording-rules-volume
              mountPath: /etc/prometheus/rules/recording_rules.yml
              subPath: recording_rules.yml
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-config
        - name: rules-volume
          configMap:
            name: prometheus-rules
        - name: recording-rules-volume
          configMap:
            name: prometheus-recording-rules
