apiVersion: v1
data:
  alerts.yml: |2-
      groups:
        - name: Alerts
          rules:
            - alert: Is Node Exporter Up?
              expr: up{job="wmi_exporter"} == 0
              for: 10s
              labels:
                severity: critical
                team: Gekko
              annotations:
                description: Instance {{ $labels.instance }} is unreachable for more than 10 seconds.
                summary: "{{ $labels.instance }} is down"
  recording_rules.yml: |-
    groups:
      - name: node exporter
        rules:
        - record: cpu:node_cpu_seconds_total
          expr: avg by(cpu) (rate(node_cpu_seconds_total[1m]))
          labels:
            exporter_name: node
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: prometheus-all-rules
