apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: grafana
  labels:
    grafana_datasource: "1"
data:
  prometheus-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.prometheus.svc.cluster.local
        isDefault: true
        editable: true
