apiVersion: v1
kind: Service
metadata:
  name: redis-commander
  namespace: redis-lab
spec:
  selector:
    app: redis-commander
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer
