apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-service
  namespace: storage
  labels:
    app: upload-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload-service
  template:
    metadata:
      labels:
        app: upload-service
    spec:
      containers:
      - name: upload-service
        image: node:18-alpine
        ports:
        - containerPort: 3000
        workingDir: /app
        command:
        - sh
        - -c
        - |
          npm install express multer minio cors
          node server.js
        volumeMounts:
        - name: app-code
          mountPath: /app
        env:
        - name: MINIO_ENDPOINT
          value: "172.16.10.243"
        - name: MINIO_PORT
          value: "9000"
        - name: MINIO_ACCESS_KEY
          value: "admin"
        - name: MINIO_SECRET_KEY
          value: "password123"
        - name: MINIO_BUCKET
          value: "profile-images"
      volumes:
      - name: app-code
        configMap:
          name: upload-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: upload-service
  namespace: storage
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  selector:
    app: upload-service
  ports:
  - port: 3000
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: upload-service-config
  namespace: storage
data:
  server.js: |
    const express = require('express');
    const multer = require('multer');
    const Minio = require('minio');
    const cors = require('cors');
    const path = require('path');

    const app = express();
    app.use(cors());
    app.use(express.json());

    // Configure MinIO client
    const minioClient = new Minio.Client({
      endPoint: process.env.MINIO_ENDPOINT,
      port: parseInt(process.env.MINIO_PORT),
      useSSL: false,
      accessKey: process.env.MINIO_ACCESS_KEY,
      secretKey: process.env.MINIO_SECRET_KEY
    });

    const bucketName = process.env.MINIO_BUCKET;

    // Ensure bucket exists
    minioClient.makeBucket(bucketName, 'us-east-1', function(err) {
      if (err) {
        console.log('Bucket already exists.');
      } else {
        console.log('Bucket created successfully.');
      }
    });

    // Configure multer for memory storage
    const upload = multer({
      storage: multer.memoryStorage(),
      limits: {
        fileSize: 5 * 1024 * 1024 // 5MB limit
      }
    });

    // Upload endpoint
    app.post('/upload', upload.single('image'), async (req, res) => {
      try {
        if (!req.file) {
          return res.status(400).json({ error: 'No file uploaded' });
        }

        const fileName = `profile_${Date.now()}_${Math.random().toString(36).substring(7)}.jpg`;
        
        // Upload to MinIO
        await minioClient.putObject(
          bucketName,
          fileName,
          req.file.buffer,
          req.file.size,
          { 'Content-Type': req.file.mimetype }
        );

        res.json({ 
          success: true, 
          filename: fileName,
          url: `http://172.16.10.243:9000/${bucketName}/${fileName}`
        });
      } catch (error) {
        console.error('Upload error:', error);
        res.status(500).json({ error: 'Upload failed' });
      }
    });

    // Get image endpoint
    app.get('/images/:filename', async (req, res) => {
      try {
        const fileName = req.params.filename;
        const stream = await minioClient.getObject(bucketName, fileName);
        res.setHeader('Content-Type', 'image/jpeg');
        stream.pipe(res);
      } catch (error) {
        console.error('Download error:', error);
        res.status(404).json({ error: 'Image not found' });
      }
    });

    // Delete image endpoint
    app.delete('/images/:filename', async (req, res) => {
      try {
        const fileName = req.params.filename;
        await minioClient.removeObject(bucketName, fileName);
        res.json({ success: true });
      } catch (error) {
        console.error('Delete error:', error);
        res.status(500).json({ error: 'Delete failed' });
      }
    });

    const PORT = process.env.PORT || 3000;
    app.listen(PORT, () => {
      console.log(`Upload service running on port ${PORT}`);
    }); 