---
# MongoDB credentials
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: razshmallow
type: Opaque
stringData:
  mongodb-root-username: razshmallow_admin
  mongodb-root-password: Razshmallow2026!SecurePass
  mongodb-database: razshmallow
