apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-exporter
  namespace: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-exporter
  template:
    metadata:
      labels:
        app: fake-exporter
    spec:
      containers:
        - name: fake-exporter
          image: prom/statsd-exporter
          ports:
            - name: metrics
              containerPort: 9102
