apiVersion: apps/v1
kind: Deployment
metadata:
  name: razshmallow-backend
  namespace: razshmallow
  labels:
    app: razshmallow-backend
    project: razshmallow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: razshmallow-backend
  template:
    metadata:
      labels:
        app: razshmallow-backend
        project: razshmallow
    spec:
      containers:
        - name: backend
          image: docker.io/bene1310/razshmallow-backend:1.0.15
          ports:
            - containerPort: 4000
              name: http
          envFrom:
            - configMapRef:
                name: razshmallow-backend-config
            - secretRef:
                name: razshmallow-backend-secret
          resources:
            requests:
              memory: "192Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /api/health
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api/health
              port: 4000
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: razshmallow-backend
  namespace: razshmallow
  labels:
    app: razshmallow-backend
spec:
  type: ClusterIP
  selector:
    app: razshmallow-backend
  ports:
    - name: http
      port: 4000
      targetPort: 4000
