# This ConfigMap contains the configuration for Alertmanager.
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: prometheus
  labels:
    app: alertmanager
data:
  alertmanager.yml: |
    global:
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'benyamine1310@gmail.com'
      smtp_auth_username: 'benyamine1310@gmail.com'
      smtp_auth_password: 'lvkzgcsaqlagydnr'
      smtp_require_tls: true

    route:
      receiver: 'urgent_receiver'
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h
      matchers:
        - severity = "critical"

    receivers:
      - name: 'urgent_receiver'
        email_configs:
          - to: 'beneytan5@gmail.com'
            send_resolved: true
