apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: prometheus
  labels:
    app: alertmanager
data:
  alertmanager.yml: |
    global:
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'beneytan@gmail.com'
      smtp_auth_username: 'beneytan@gmail.com'
      smtp_auth_password: 'dqtovhgqzqvoyvxn'
      smtp_require_tls: true

    route:
      receiver: default
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h
      routes:
        - matchers:
            - severity = "critical"
          receiver: urgent_receiver

    receivers:
      - name: default
        email_configs:
          - to: 'beneytan5@gmail.com'
            send_resolved: true

      - name: urgent_receiver
        email_configs:
          - to: 'beneytan5@gmail.com'
            send_resolved: true
