# This ConfigMap contains the configuration for Alertmanager.
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: prometheus
  labels:
    app: alertmanager
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: default
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h

    receivers:
      - name: default
        email_configs:
          - to: 'your@email.com'
            from: 'alertmanager@lab.local'
            smarthost: 'smtp.example.com:587'
            auth_username: 'user'
            auth_identity: 'user'
            auth_password: 'password'
