apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: prometheus
  labels:
    app: alertmanager
data:
  alertmanager.yml: |
    global:
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'beneytan@gmail.com'
      smtp_auth_username: 'beneytan@gmail.com'
      smtp_auth_password: 'dqtovhgqzqvoyvxn'
      smtp_require_tls: true

    route:
      receiver: main_receiver


      routes:
          receiver: 'urgent_receiver'
        - matchers:
            - severity="critical"

    receivers:
      - name: 'main_receiver'
        email_configs:
          - to: 'beneytan5@gmail.com'

      - name: 'urgent_receiver'
        email_configs:
          - to: 'beneytan5@gmail.com'
