# alertmanager-lb.yaml
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-lb
  namespace: prometheus
spec:
  selector:
    app: alertmanager
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 9093
  type: LoadBalancer
  loadBalancerIP: 172.16.10.207  # your MetalLB IP
