# alertmanager-clusterip.yaml
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: prometheus
spec:
  selector:
    app: alertmanager
  ports:
    - name: web
      protocol: TCP
      port: 9093
      targetPort: 9093
  type: ClusterIP
