apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-alert-rule
  namespace: prometheus
  labels:
    release: prometheus
spec:
  groups:
    - name: always-firing
      rules:
        - alert: AlwaysFiring
          expr: vector(1)
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Test alert from Prometheus"
