apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: prometheus
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 9090
      nodePort: 30090  # You can choose any available port in range 30000–32767