apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: prometheus
spec:
  replicas: 1
  serviceAccountName: prometheus-sa
  serviceMonitorSelector:
    matchLabels:
      release: prometheus
  serviceMonitorNamespaceSelector:
    matchNames:
      - prometheus
  resources: {}
  enableAdminAPI: true
