apiVersion: v1
kind: Secret
metadata:
  name: pg-backup-secret
  namespace: postgres
type: Opaque
stringData:
  PGHOST: "postgres.postgres.svc.cluster.local"  # <-- your service DNS
  PGPORT: "5432"
  PGDATABASE: "mydb"
  PGUSER: "postgres"
  PGPASSWORD: "Q1w2e3r4"