apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-backup-nfs-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - vers=3
    - tcp
  nfs:
    server: 10.0.0.100
    path: /pg-backups