apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keepass
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bene1310/k8s-apps
    targetRevision: HEAD
    path: base/keepass
  destination:
    server: https://kubernetes.default.svc
    namespace: keepass_app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
