apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
spec:
  project: default
  source:
    repoURL: https://github.com/bene1310/k8s-apps
    targetRevision: HEAD
    path: base/minio
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
