apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: mongodb
spec:
  project: default
  source:
    repoURL: https://github.com/bene1310/k8s-apps
    targetRevision: HEAD
    path: base/mongodb
  destination:
    server: https://kubernetes.default.svc
    namespace: mongodb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
