apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    namespace: prometheus
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/BenE1310/k8s-apps.git
    targetRevision: HEAD
    path: monitoring/prometheus
  syncPolicy:
    automated:
      selfHeal: true