apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-state-metrics
  namespace: prometheus
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics   # use more standard label if applicable
  endpoints:
    - port: http
      interval: 15s
  namespaceSelector:
    matchNames:
      - kube-system       # <== FIXED
