apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: postgres
  annotations:
    metallb.universe.tf/loadBalancerIPs: 172.16.10.206
spec:
  selector:
    app: pgadmin
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
